name: Post Tweet Every 2 Hours

on:
  schedule:
    - cron: "0 */2 * * *" # Esegue il workflow ogni 2 ore
  workflow_dispatch: # Permette esecuzione manuale

jobs:
  post_tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tweet script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          python main.py  # Sostituisci con python tournament.py se necessario

      - name: Commit and push updated data
        env:
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}  # Usa il secret qui
        run: |
          git config --global user.name "RPS World Bot"
          git config --global user.email "$GIT_EMAIL"  # Riferimento alla variabile d'ambiente
          git add data.json tournament_history.json
          git commit -m "Update tournament state - $(date)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}