name: Post Tweet Every 2 Hours

on:
  schedule:
    - cron: "0 */2 * * *" # Esegue il workflow ogni 2 ore
  workflow_dispatch: # Permette esecuzione manuale

jobs:
  post_tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tweet script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          python main.py  # O python tournament.py

      - name: Commit and push updated data
        env:
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "RPS World Bot"
          git config --global user.email "$GIT_EMAIL"
          # Aggiunge i file solo se esistono
          [ -f data.json ] && git add data.json || echo "data.json not found, skipping"
          [ -f tournament_history.json ] && git add tournament_history.json || echo "tournament_history.json not found, skipping"
          git commit -m "Update tournament state - $(date)" || echo "No changes to commit"
          git push
